# Meta data
name:         iCENTER
authors:      Dauren Amanbayev
description:  Образовательный центр

# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Server
source:       docs
port:         4000
url:          http://daurenamanbayev.github.io
