# Meta data
name:         ICENTER
authors:      Dauren Amanbayev
description:  English for everyone!

# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Server
source:       docs
port:         4000
url:          http://daurenamanbayev.github.io
