# Meta data
name:         iCENTER - Образовательный центр английского языка в Астане
authors:      Dauren Amanbayev
description:  Языковые курсы английского языка в Астане. Подготовка к международным экзаменам (IELTS, TOEFL, GMAT). Подготовка на поступление в Казахско-Турецкий лицей, Назарбаевскую школу, Назарбаев университет.  

# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Server
source:       docs
port:         4000
url:          http://icenter-edu.com
