# Meta data
name:         iCENTER
authors:      Dauren Amanbayev
description:  Образовательный центр английского языка в Астане

# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Server
source:       docs
port:         4000
url:          http://icenter-edu.com
